"""add role to usuarios

Revision ID: 02a3d834e7f4
Revises: 226ffb0ab03b
Create Date: 2026-07-18 14:03:39.435615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a3d834e7f4'
down_revision: Union[str, Sequence[str], None] = '226ffb0ab03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE usuarios SET role = 'operador' WHERE role IS NULL")
    op.alter_column('usuarios', 'role', nullable=False)




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
