"""create tabelas iniciais

Revision ID: 226ffb0ab03b
Revises: 
Create Date: 2026-07-10 00:45:57.682621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226ffb0ab03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(), nullable=True),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SAIDA', 'PENDENCIA', 'ENTREGA', 'CANCELAMENTO', name='statusproduto'), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_codigo_rastreio'), 'produtos', ['codigo_rastreio'], unique=True)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_foreign_key(None, 'historico_status', 'produtos', ['produto_id'], ['id'])
    op.create_foreign_key(None, 'historico_status', 'usuarios', ['alterado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historico_status', type_='foreignkey')
    op.drop_constraint(None, 'historico_status', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_rastreio'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
