"""add tokens confirmacao

Revision ID: 6e1fd8a9e308
Revises: 8d390df09ceb
Create Date: 2026-09-03 10:40:04.563254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1fd8a9e308'
down_revision: Union[str, Sequence[str], None] = '8d390df09ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_confirmacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_confirmacao_id'), 'tokens_confirmacao', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_confirmacao_token'), 'tokens_confirmacao', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_confirmacao_token'), table_name='tokens_confirmacao')
    op.drop_index(op.f('ix_tokens_confirmacao_id'), table_name='tokens_confirmacao')
    op.drop_table('tokens_confirmacao')
    # ### end Alembic commands ###
