"""add tokens recuperacao

Revision ID: 7674450470bd
Revises: 6e1fd8a9e308
Create Date: 2026-09-07 22:22:07.135973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7674450470bd'
down_revision: Union[str, Sequence[str], None] = '6e1fd8a9e308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('cep', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('logradouro', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('numero', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('complemento_tipo', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('complemento', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('bairro', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('cidade', sa.String(), nullable=True))
    op.add_column('produtos', sa.Column('estado', sa.String(), nullable=True))
    op.drop_column('produtos', 'endereco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('produtos', 'estado')
    op.drop_column('produtos', 'cidade')
    op.drop_column('produtos', 'bairro')
    op.drop_column('produtos', 'complemento')
    op.drop_column('produtos', 'complemento_tipo')
    op.drop_column('produtos', 'numero')
    op.drop_column('produtos', 'logradouro')
    op.drop_column('produtos', 'cep')
    # ### end Alembic commands ###
