"""add motorista to produto

Revision ID: 8d390df09ceb
Revises: 7d19d382c1b9
Create Date: 2026-07-22 11:46:10.327400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d390df09ceb'
down_revision: Union[str, Sequence[str], None] = '7d19d382c1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('motorista_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produtos', 'usuarios', ['motorista_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'motorista_id')
    # ### end Alembic commands ###
